version: "3.8"

services:
  management-ui-asset:
    image: mrflick72/vauthenticator-management-ui-assets-k8s
    ports:
      - "3001:80"
  auth-server-asset:
    image: mrflick72/vauthenticator-assets-k8s
    ports:
      - "3000:80"
  redis:
    image: redis
    ports:
      - "6379:6379"
  mail-server:
    image: apache/james:demo-3.7.3
    ports:
      - "587:587"
      - "465:465"
      - "993:993"